name: Build Example CI

on:
  workflow_dispatch:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, riscv64, aarch64, loongarch64]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Test ${{ matrix.arch }}
      run: cd example && make ARCH=${{ matrix.arch }} build
